const INCOME_KEY='ppob.income.v1',EXPENSE_KEY='ppob.expense.v1';
let incomeData=JSON.parse(localStorage.getItem(INCOME_KEY)||'[]'),expenseData=JSON.parse(localStorage.getItem(EXPENSE_KEY)||'[]'),incomeEditing=null,expenseEditing=null,$=x=>document.getElementById(x),fmt=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n),today=()=>{let d=new Date();return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()},monthKey=()=>{let d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')},recordMonth=r=>{let p=String(r.date||'').split('/');return p.length===3?p[2]+'-'+p[1]:''};
$('date').value=today();$('expenseDate').value=today();$('month').value=monthKey();

function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderDashboard(){let m=$('month').value||monthKey(),inc=incomeData.filter(r=>recordMonth(r)===m),exp=expenseData.filter(r=>recordMonth(r)===m),it=inc.reduce((a,r)=>a+Number(r.amount),0),et=exp.reduce((a,r)=>a+Number(r.amount),0);$('monthlyIncome').textContent=fmt(it);$('monthlyExpense').textContent=fmt(et);$('monthlyNet').textContent=fmt(it-et);$('monthlyIncomeCount').textContent=inc.length;$('monthlyExpenseCount').textContent=exp.length}
function renderIncome(){if(!incomeData.length){$('table').innerHTML='<p class="muted">No income records yet.</p>';return}$('table').innerHTML='<table><tr><th>Item name</th><th>Qty</th><th class="money">Income amount</th><th>Date</th><th>Note</th><th>Action</th></tr>'+incomeData.map(r=>'<tr><td>'+esc(r.item)+'</td><td>'+r.qty+'</td><td class="money">'+fmt(r.amount)+'</td><td>'+r.date+'</td><td>'+esc(r.note)+'</td><td><button onclick="editIncome(\''+r.id+'\')">Edit</button><button onclick="delIncome(\''+r.id+'\')">Delete</button></td></tr>').join('')+'</table>'}
function renderExpenses(){if(!expenseData.length){$('expenseTable').innerHTML='<p class="muted">No expense records yet.</p>';return}$('expenseTable').innerHTML='<table><tr><th>Expense name</th><th class="money">Amount</th><th>Date</th><th>Note</th><th>Action</th></tr>'+expenseData.map(r=>'<tr><td>'+esc(r.item)+'</td><td class="money">'+fmt(r.amount)+'</td><td>'+r.date+'</td><td>'+esc(r.note)+'</td><td><button onclick="editExpense(\''+r.id+'\')">Edit</button><button onclick="delExpense(\''+r.id+'\')">Delete</button></td></tr>').join('')+'</table>'}

$('incomeForm').onsubmit=e=>{e.preventDefault();let r={item:$('item').value.trim(),qty:+$('qty').value,amount:+$('amount').value,date:$('date').value,note:$('note').value.trim()};if(incomeEditing){let i=incomeData.findIndex(x=>x.id===incomeEditing);incomeData[i]={...incomeData[i],...r};incomeEditing=null;e.target.querySelector('button').textContent='Add income'}else incomeData.push({id:crypto.randomUUID(),...r});localStorage.setItem(INCOME_KEY,JSON.stringify(incomeData));e.target.reset();$('qty').value=1;$('date').value=today();renderIncome();renderDashboard()};
window.editIncome=id=>{let r=incomeData.find(x=>x.id===id);incomeEditing=id;$('item').value=r.item;$('qty').value=r.qty;$('amount').value=r.amount;$('date').value=r.date;$('note').value=r.note;$('incomeForm').querySelector('button').textContent='Save changes'};
window.delIncome=id=>{if(confirm('Delete this income record?')){incomeData=incomeData.filter(x=>x.id!==id);localStorage.setItem(INCOME_KEY,JSON.stringify(incomeData));renderIncome();renderDashboard()}};

$('expenseForm').onsubmit=e=>{e.preventDefault();let r={item:$('expenseItem').value.trim(),amount:+$('expenseAmount').value,date:$('expenseDate').value,note:$('expenseNote').value.trim()};if(expenseEditing){let i=expenseData.findIndex(x=>x.id===expenseEditing);expenseData[i]={...expenseData[i],...r};expenseEditing=null;e.target.querySelector('button').textContent='Add expense'}else expenseData.push({id:crypto.randomUUID(),...r});localStorage.setItem(EXPENSE_KEY,JSON.stringify(expenseData));e.target.reset();$('expenseDate').value=today();renderExpenses();renderDashboard()};
window.editExpense=id=>{let r=expenseData.find(x=>x.id===id);expenseEditing=id;$('expenseItem').value=r.item;$('expenseAmount').value=r.amount;$('expenseDate').value=r.date;$('expenseNote').value=r.note;$('expenseForm').querySelector('button').textContent='Save changes'};
window.delExpense=id=>{if(confirm('Delete this expense record?')){expenseData=expenseData.filter(x=>x.id!==id);localStorage.setItem(EXPENSE_KEY,JSON.stringify(expenseData));renderExpenses();renderDashboard()}};

function show(p){$('dashboard').hidden=p!=='dashboard';$('income').hidden=p!=='income';$('expenses').hidden=p!=='expenses';$('bd').classList.toggle('active',p==='dashboard');$('bi').classList.toggle('active',p==='income');$('be').classList.toggle('active',p==='expenses');if(p==='income')$('date').value=today();if(p==='expenses')$('expenseDate').value=today();if(p==='dashboard')renderDashboard()}
$('bd').onclick=()=>show('dashboard');$('bi').onclick=()=>show('income');$('be').onclick=()=>show('expenses');$('month').onchange=renderDashboard;
$('toggleSidebar').onclick=()=>{let c=$('sidebar').classList.toggle('collapsed');$('toggleSidebar').textContent=c?'›':'‹';$('toggleSidebar').title=c?'Expand sidebar':'Collapse sidebar';$('toggleSidebar').setAttribute('aria-label',$('toggleSidebar').title)};
renderIncome();renderExpenses();renderDashboard();